### ISSUE TITLE
Add Generics for passing other kind of list

### ISSUE THREAD

**Issue by wer-mathurin** [SphericalKat/dart-fuzzywuzzy#1]
@SphericalKat,

very good first implementation and easy to use;

Add the capability of passing:
List<T> instead of a list of String

When providing a generic List, we must provide a getter function for the search => String Function(T)

You can also parametrize the class ExtractedResult<T> and add a property let say 
final T original;

By doing this we would not require to convert the original list of Something to a list a String and convert it again to a List of Something.

**Comment by SphericalKat** [comment]
Got it, I'll be working on this soon :)

**Comment by SphericalKat** [comment]
Closed in f1d0d24.
